name: "DEV DEPLOY"

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::429955619436:role/github-actions-ViniciusAdams-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "viniciusadams-virginia-terraform"
      aws-lock-dynamodb-table: "viniciusadams-virginia-terraform-lock"